'http://water.sam.usace.army.mil/gage/acf/prob1' + '.txt'
+ '-(56-

In [1]:
import csv
import ssl
import urllib.request

import pandas as pd

ssl._create_default_https_context = ssl._create_unverified_context

The current year can always be found at http://water.sam.usace.army.mil/gage/acf/prob1.txt

Records go back as far as February 8, 1956. Structure of URL for older files is:
http://water.sam.usace.army.mil/gage/acf/prob1- + last 2 digits of year + '.txt'

Data is in .txt format but is separated out in an unusual fashion - varying whitespace rather than purely commas or tabs or newlines. Will try to use pandas to take in the data initially, but will likely just extract the first 28 rows to start.

In [11]:
current_year = 'http://water.sam.usace.army.mil/gage/acf/prob1.txt'

with urllib.request.urlopen(current_year) as f:
    df_thisyear = pd.read_csv(f, skiprows=[0,1,2,3,36,37,38],
                    delim_whitespace=True,
                    index_col=0,
                    names=['Day', 'October', 'November', 'December', 'January',
                          'February', 'March', 'April', 'May', 'June', 'July',
                          'August', 'September']).fillna('')

In [12]:
df_thisyear

,October,November,December,January,February,March,April,May,June,July,August,September
Day,,,,,,,,,,,,
1,1067.66,1067.52,,,,,,,,,,
2,1067.60,1067.56,,,,,,,,,,
3,1067.53,1067.59,,,,,,,,,,
4,1067.46,1067.58,,,,,,,,,,
5,1067.43,1067.54,,,,,,,,,,
6,1067.39,1067.54,,,,,,,,,,
7,1067.30,1067.54,,,,,,,,,,
8,1067.25,1067.55,,,,,,,,,,
9,1067.20,1067.51,,,,,,,,,,
10,1067.15,1067.51,,,,,,,,,,
11,1067.07,1067.51,,,,,,,,,,
12,1067.03,1067.48,,,,,,,,,,
13,1067.09,1067.41,,,,,,,,,,
14,1067.02,1067.39,,,,,,,,,,
15,1066.97,1067.39,,,,,,,,,,
16,1066.94,,,,,,,,,,,
17,1066.89,,,,,,,,,,,
18,1066.89,,,,,,,,,,,
19,1066.84,,,,,,,,,,,
20,1066.89,,,,,,,,,,,
21,1066.86,,,,,,,,,,,
22,1066.80,,,,,,,,,,,
23,1066.77,,,,,,,,,,,
24,1066.73,,,,,,,,,,,
25,1066.69,,,,,,,,,,,
26,1066.72,,,,,,,,,,,
27,1066.75,,,,,,,,,,,
28,1066.73,,,,,,,,,,,
29,1066.73,,,,,,,,,,,
30,1066.94,,,,,,,,,,,
31,1067.37,,,,,,,,,,,

In [5]:
df_thisyear['November'][1]

1067.52

In [9]:
last_year = 'http://water.sam.usace.army.mil/gage/acf/prob1-19.txt'

with urllib.request.urlopen(last_year) as g:
    df_lastyear = pd.read_csv(g, skiprows=[0,1,2,3,33,34,35,36,37,38],
                    delim_whitespace=True,
                    index_col=0,
                    names=['Day', 'October', 'November', 'December', 'January',
                          'February', 'March', 'April', 'May', 'June', 'July',
                          'August', 'September']).fillna('')

In [10]:
df_lastyear

,October,November,December,January,February,March,April,May,June,July,August,September
Day,,,,,,,,,,,,
1,1070.05,1069.33,1070.67,1073.89,1071.83,1075.65,1072.47,1072.15,1070.80,1071.28,1070.74,1069.64
2,1070.00,1069.32,1071.01,1073.87,1071.79,1075.57,1072.41,1071.98,1070.81,1071.23,1070.72,1069.59
3,1069.93,1069.34,1070.90,1074.17,1071.90,1075.88,1072.38,1071.83,1070.76,1071.17,1070.69,1069.51
4,1069.86,1069.36,1070.68,1074.69,1072.00,1075.99,1072.40,1071.98,1070.73,1071.13,1070.79,1069.45
5,1069.82,1069.33,1070.57,1074.68,1072.10,1075.85,1072.50,1072.00,1070.73,1071.10,1070.74,1069.37
6,1069.79,1069.36,1070.39,1074.50,1071.91,1075.63,1072.51,1071.95,1070.78,1071.13,1070.70,1069.30
7,1069.75,1069.37,1070.23,1074.29,1071.67,1075.46,1072.60,1071.92,1070.90,1071.14,1070.66,1069.26
8,1069.69,1069.40,1070.58,1074.04,1071.39,1075.32,1072.61,1071.83,1071.27,1071.14,1070.60,1069.22
9,1069.63,1069.52,1071.35,1073.78,1071.24,1075.22,1072.53,1071.77,1071.47,1071.15,1070.55,1069.15
10,1069.81,1069.61,1071.34,1073.52,1071.06,1075.02,1072.42,1071.66,1071.69,1071.11,1070.55,1069.06
11,1069.88,1069.62,1071.12,1073.27,1071.21,1074.84,1072.29,1071.86,1071.72,1071.20,1070.54,1068.96
12,1069.85,1070.65,1070.89,1073.15,1071.58,1074.65,1072.14,1072.02,1071.61,1071.31,1070.48,1068.91
13,1069.85,1071.13,1070.72,1073.12,1071.61,1074.44,1072.04,1072.01,1071.57,1071.39,1070.40,1068.83
14,1069.81,1071.42,1070.91,1072.92,1071.38,1074.30,1072.14,1071.89,1071.53,1071.42,1070.43,1068.78
15,1069.74,1071.52,1070.84,1072.64,1071.38,1074.29,1072.19,1071.80,1071.55,1071.38,1070.40,1068.74
16,1069.71,1071.37,1070.63,1072.37,1071.62,1074.11,1072.07,1071.68,1071.59,1071.32,1070.37,1068.65
17,1069.67,1071.16,1070.50,1072.27,1071.82,1073.91,1071.97,1071.56,1071.56,1071.27,1070.34,1068.61
18,1069.65,1070.92,1070.30,1072.15,1072.11,1073.68,1072.04,1071.50,1071.67,1071.24,1070.31,1068.53
19,1069.58,1070.64,1070.18,1072.37,1072.73,1073.45,1073.04,1071.46,1071.65,1071.21,1070.26,1068.44
20,1069.54,1070.54,1070.39,1072.75,1073.34,1073.22,1073.53,1071.32,1071.62,1071.21,1070.21,1068.36
21,1069.52,1070.48,1070.70,1072.64,1074.61,1072.98,1073.48,1071.17,1071.57,1071.21,1070.16,1068.31
22,1069.46,1070.46,1070.76,1072.47,1075.50,1072.77,1073.38,1071.07,1071.62,1071.14,1070.09,1068.27
23,1069.38,1070.47,1070.77,1072.72,1075.84,1072.70,1073.27,1070.97,1071.64,1071.15,1070.03,1068.20
24,1069.35,1070.50,1070.76,1073.12,1076.10,1072.67,1073.12,1070.93,1071.57,1071.09,1070.05,1068.13
25,1069.31,1070.50,1070.72,1072.96,1076.00,1072.65,1073.07,1070.93,1071.48,1071.02,1070.01,1068.06
26,1069.44,1070.50,1070.68,1072.76,1075.84,1072.65,1072.99,1070.93,1071.42,1070.94,1069.98,1067.96
27,1069.46,1070.43,1070.76,1072.56,1075.67,1072.61,1072.83,1070.88,1071.39,1070.90,1069.93,1067.89
28,1069.46,1070.35,1072.98,1072.46,1075.74,1072.57,1072.64,1070.85,1071.35,1070.87,1069.86,1067.85

In [8]:
import re

with urllib.request.urlopen(last_year) as h:
    for line in h:
        print(repr(line))

b'\x0c\r\n'
b'                                                   MIDNIGHT POOLS AT BUFORD\r\n'
b'                                                         2019  WATER YEAR\r\n'
b'       OCT        NOV       DEC       JAN       FEB       MAR       APR       MAY       JUN       JUL       AUG       SEP\r\n'
b' \r\n'
b'  1    1070.05   1069.33   1070.67   1073.89   1071.83   1075.65   1072.47   1072.15   1070.80   1071.28   1070.74   1069.64\r\n'
b'  2    1070.00   1069.32   1071.01   1073.87   1071.79   1075.57   1072.41   1071.98   1070.81   1071.23   1070.72   1069.59\r\n'
b'  3    1069.93   1069.34   1070.90   1074.17   1071.90   1075.88   1072.38   1071.83   1070.76   1071.17   1070.69   1069.51\r\n'
b'  4    1069.86   1069.36   1070.68   1074.69   1072.00   1075.99   1072.40   1071.98   1070.73   1071.13   1070.79   1069.45\r\n'
b'  5    1069.82   1069.33   1070.57   1074.68   1072.10   1075.85   1072.50   1072.00   1070.73   1071.10   1070.74   1069.37\r\n'
b'  6    1069.79   1069.36   1070.39   1074.50   1071.91   1075.63   1072.51   1071.95   1070.78   1071.13   1070.70   1069.30\r\n'
b'  7    1069.75   1069.37   1070.23   1074.29   1071.67   1075.46   1072.60   1071.92   1070.90   1071.14   1070.66   1069.26\r\n'
b'  8    1069.69   1069.40   1070.58   1074.04   1071.39   1075.32   1072.61   1071.83   1071.27   1071.14   1070.60   1069.22\r\n'
b'  9    1069.63   1069.52   1071.35   1073.78   1071.24   1075.22   1072.53   1071.77   1071.47   1071.15   1070.55   1069.15\r\n'
b' 10    1069.81   1069.61   1071.34   1073.52   1071.06   1075.02   1072.42   1071.66   1071.69   1071.11   1070.55   1069.06\r\n'
b' 11    1069.88   1069.62   1071.12   1073.27   1071.21   1074.84   1072.29   1071.86   1071.72   1071.20   1070.54   1068.96\r\n'
b' 12    1069.85   1070.65   1070.89   1073.15   1071.58   1074.65   1072.14   1072.02   1071.61   1071.31   1070.48   1068.91\r\n'
b' 13    1069.85   1071.13   1070.72   1073.12   1071.61   1074.44   1072.04   1072.01   1071.57   1071.39   1070.40   1068.83\r\n'
b' 14    1069.81   1071.42   1070.91   1072.92   1071.38   1074.30   1072.14   1071.89   1071.53   1071.42   1070.43   1068.78\r\n'
b' 15    1069.74   1071.52   1070.84   1072.64   1071.38   1074.29   1072.19   1071.80   1071.55   1071.38   1070.40   1068.74\r\n'
b' 16    1069.71   1071.37   1070.63   1072.37   1071.62   1074.11   1072.07   1071.68   1071.59   1071.32   1070.37   1068.65\r\n'
b' 17    1069.67   1071.16   1070.50   1072.27   1071.82   1073.91   1071.97   1071.56   1071.56   1071.27   1070.34   1068.61\r\n'
b' 18    1069.65   1070.92   1070.30   1072.15   1072.11   1073.68   1072.04   1071.50   1071.67   1071.24   1070.31   1068.53\r\n'
b' 19    1069.58   1070.64   1070.18   1072.37   1072.73   1073.45   1073.04   1071.46   1071.65   1071.21   1070.26   1068.44\r\n'
b' 20    1069.54   1070.54   1070.39   1072.75   1073.34   1073.22   1073.53   1071.32   1071.62   1071.21   1070.21   1068.36\r\n'
b' 21    1069.52   1070.48   1070.70   1072.64   1074.61   1072.98   1073.48   1071.17   1071.57   1071.21   1070.16   1068.31\r\n'
b' 22    1069.46   1070.46   1070.76   1072.47   1075.50   1072.77   1073.38   1071.07   1071.62   1071.14   1070.09   1068.27\r\n'
b' 23    1069.38   1070.47   1070.77   1072.72   1075.84   1072.70   1073.27   1070.97   1071.64   1071.15   1070.03   1068.20\r\n'
b' 24    1069.35   1070.50   1070.76   1073.12   1076.10   1072.67   1073.12   1070.93   1071.57   1071.09   1070.05   1068.13\r\n'
b' 25    1069.31   1070.50   1070.72   1072.96   1076.00   1072.65   1073.07   1070.93   1071.48   1071.02   1070.01   1068.06\r\n'
b' 26    1069.44   1070.50   1070.68   1072.76   1075.84   1072.65   1072.99   1070.93   1071.42   1070.94   1069.98   1067.96\r\n'
b' 27    1069.46   1070.43   1070.76   1072.56   1075.67   1072.61   1072.83   1070.88   1071.39   1070.90   1069.93   1067.89\r\n'
b' 28    1069.46   1070.35   1072.98   1072.46   1075.74   1072.57   1072.64   1070.85   1071.35   1070.87   1069.86   1067.85\r\n'
b' 29    1069.38   1070.33   1073.39   1072.58             1072.52   1072.46   1070.85   1071.35   1070.82   1069.79   1067.81\r\n'
b' 30    1069.36   1070.30   1073.58   1072.39             1072.49   1072.31   1070.83   1071.35   1070.77   1069.71   1067.73\r\n'
b' 31    1069.33             1073.80   1072.12             1072.47             1070.79             1070.72   1069.68\r\n'
b'AVG    1069.65   1070.24   1071.07   1073.14   1072.89   1074.05   1072.59   1071.50   1071.36   1071.13   1070.32   1068.69\r\n'
b'MAX    1070.05   1071.52   1073.80   1074.69   1076.10   1075.99   1073.53   1072.15   1071.72   1071.42   1070.79   1069.64\r\n'
b'MIN    1069.31   1069.32   1070.18   1072.12   1071.06   1072.47   1071.97   1070.79   1070.73   1070.72   1069.68   1067.73\r\n'
b' \r\n'
b' \r\n'
b' \r\n'
b' \r\n'

Going to try using the csv module to scan things in...