'http://water.sam.usace.army.mil/gage/acf/prob1' + '.txt'
+ '-(56-

In [4]:
import csv
import urllib.request

import pandas as pd

The current year can always be found at http://water.sam.usace.army.mil/gage/acf/prob1.txt

Records go back as far as February 8, 1956. Structure of URL for older files is:
http://water.sam.usace.army.mil/gage/acf/prob1- + last 2 digits of year + '.txt'

Data is in .txt format but is separated out in an unusual fashion - varying whitespace rather than purely commas or tabs or newlines. Will try to use pandas to take in the data initially, but will likely just extract the first 28 rows to start.

In [2]:
current_year = 'http://water.sam.usace.army.mil/gage/acf/prob1.txt'

with urllib.request.urlopen(current_year) as f:
    df_thisyear = pd.read_csv(f, skiprows=[0,1,2,3,33,34,35,36,37,38],
                    delim_whitespace=True,
                    index_col=0,
                    names=['Day', 'October', 'November', 'December', 'January',
                          'February', 'March', 'April', 'May', 'June', 'July',
                          'August', 'September']).fillna('')

In [3]:
df_thisyear

,October,November,December,January,February,March,April,May,June,July,August,September
Day,,,,,,,,,,,,
1,1070.05,1069.33,1070.67,1073.89,1071.83,1075.65,1072.47,1072.15,1070.80,1071.28,1070.74,
2,1070.00,1069.32,1071.01,1073.87,1071.79,1075.57,1072.41,1071.98,1070.81,1071.23,1070.72,
3,1069.93,1069.34,1070.90,1074.17,1071.90,1075.88,1072.38,1071.83,1070.76,1071.17,1070.69,
4,1069.86,1069.36,1070.68,1074.69,1072.00,1075.99,1072.40,1071.98,1070.73,1071.13,1070.79,
5,1069.82,1069.33,1070.57,1074.68,1072.10,1075.85,1072.50,1072.00,1070.73,1071.10,1070.74,
6,1069.79,1069.36,1070.39,1074.50,1071.91,1075.63,1072.51,1071.95,1070.78,1071.13,1070.7,
7,1069.75,1069.37,1070.23,1074.29,1071.67,1075.46,1072.60,1071.92,1070.90,1071.14,1070.66,
8,1069.69,1069.40,1070.58,1074.04,1071.39,1075.32,1072.61,1071.83,1071.27,1071.14,1070.6,
9,1069.63,1069.52,1071.35,1073.78,1071.24,1075.22,1072.53,1071.77,1071.47,1071.15,1070.55,
10,1069.81,1069.61,1071.34,1073.52,1071.06,1075.02,1072.42,1071.66,1071.69,1071.11,1070.55,
11,1069.88,1069.62,1071.12,1073.27,1071.21,1074.84,1072.29,1071.86,1071.72,1071.20,1070.54,
12,1069.85,1070.65,1070.89,1073.15,1071.58,1074.65,1072.14,1072.02,1071.61,1071.31,,
13,1069.85,1071.13,1070.72,1073.12,1071.61,1074.44,1072.04,1072.01,1071.57,1071.39,,
14,1069.81,1071.42,1070.91,1072.92,1071.38,1074.30,1072.14,1071.89,1071.53,1071.42,,
15,1069.74,1071.52,1070.84,1072.64,1071.38,1074.29,1072.19,1071.80,1071.55,1071.38,,
16,1069.71,1071.37,1070.63,1072.37,1071.62,1074.11,1072.07,1071.68,1071.59,1071.32,,
17,1069.67,1071.16,1070.50,1072.27,1071.82,1073.91,1071.97,1071.56,1071.56,1071.27,,
18,1069.65,1070.92,1070.30,1072.15,1072.11,1073.68,1072.04,1071.50,1071.67,1071.24,,
19,1069.58,1070.64,1070.18,1072.37,1072.73,1073.45,1073.04,1071.46,1071.65,1071.21,,
20,1069.54,1070.54,1070.39,1072.75,1073.34,1073.22,1073.53,1071.32,1071.62,1071.21,,
21,1069.52,1070.48,1070.70,1072.64,1074.61,1072.98,1073.48,1071.17,1071.57,1071.21,,
22,1069.46,1070.46,1070.76,1072.47,1075.50,1072.77,1073.38,1071.07,1071.62,1071.14,,
23,1069.38,1070.47,1070.77,1072.72,1075.84,1072.70,1073.27,1070.97,1071.64,1071.15,,
24,1069.35,1070.50,1070.76,1073.12,1076.10,1072.67,1073.12,1070.93,1071.57,1071.09,,
25,1069.31,1070.50,1070.72,1072.96,1076.00,1072.65,1073.07,1070.93,1071.48,1071.02,,
26,1069.44,1070.50,1070.68,1072.76,1075.84,1072.65,1072.99,1070.93,1071.42,1070.94,,
27,1069.46,1070.43,1070.76,1072.56,1075.67,1072.61,1072.83,1070.88,1071.39,1070.90,,
28,1069.46,1070.35,1072.98,1072.46,1075.74,1072.57,1072.64,1070.85,1071.35,1070.87,,

In [4]:
df['November'][1]

1069.33

In [14]:
last_year = 'http://water.sam.usace.army.mil/gage/acf/prob1-18.txt'

with urllib.request.urlopen(last_year) as g:
    df_lastyear = pd.read_csv(g, skiprows=[0,1,2,3,36,37,38],
                    delim_whitespace=True,
                    index_col=0,
                    names=['Day', 'October', 'November', 'December', 'January',
                          'February', 'March', 'April', 'May', 'June', 'July',
                          'August', 'September']).fillna('')

In [15]:
df_lastyear

,October,November,December,January,February,March,April,May,June,July,August,September
Day,,,,,,,,,,,,
1,1065.11,1065.57,1065.46,1065.99,1066.50,1070.80,1070.65,1071.8,1074.6,1072.13,1071.75,1070.82
2,1065.06,1065.58,1065.45,1065.99,1066.48,1070.79,1070.60,1071.77,1074.69,1072.12,1071.98,1070.8
3,1065.00,1065.57,1065.43,1065.95,1066.52,1070.75,1070.55,1071.7,1074.62,1072.08,1072.29,1070.82
4,1064.94,1065.57,1065.42,1065.95,1066.97,1070.68,1070.51,1071.65,1074.46,1072.08,1072.38,1070.74
5,1064.90,1065.59,1065.41,1065.91,1067.04,1070.63,1070.53,1071.63,1074.25,1072.07,1072.49,1070.72
6,1064.87,1065.57,1065.41,1065.93,1067.08,1070.66,1070.53,1071.61,1073.97,1072.1,1072.47,1070.69
7,1064.84,1065.58,1065.40,1065.91,1067.72,1070.65,1070.54,1071.57,1073.7,1072.09,1072.52,1070.65
8,1065.04,1065.61,1065.51,1065.91,1067.96,1070.62,1070.57,1071.52,1073.46,1072.08,1072.52,1070.62
9,1065.19,1065.64,1065.52,1065.91,1068.10,1070.57,1070.57,1071.47,1073.28,1072.03,1072.39,1070.61
10,1065.23,1065.70,1065.52,1065.92,1068.23,1070.56,1070.56,1071.41,1073.16,1071.99,1072.26,1070.61
11,1065.24,1065.67,1065.51,1065.96,1068.96,1070.59,1070.55,1071.36,1072.99,1071.95,1072.26,1070.65
12,1065.23,1065.64,1065.50,1066.03,1069.54,1070.64,1070.50,1071.3,1072.73,1071.91,1072.27,1070.65
13,1065.22,1065.64,1065.47,1066.10,1069.77,1070.60,1070.42,1071.23,1072.5,1071.89,1072.14,1070.61
14,1065.20,1065.65,1065.46,1066.14,1069.92,1070.59,1070.31,1071.17,1072.45,1071.9,1071.97,1070.57
15,1065.20,1065.62,1065.46,1066.15,1070.05,1070.60,1070.38,1071.16,1072.45,1071.89,1071.84,1070.55
16,1065.21,1065.61,1065.45,1066.13,1070.15,1070.63,1070.40,1071.44,1072.49,1071.9,1071.68,1070.54
17,1065.19,1065.61,1065.46,1066.16,1070.26,1070.68,1070.38,1071.53,1072.5,1071.9,1071.52,1070.5
18,1065.15,1065.59,1065.43,1066.14,1070.39,1070.70,1070.40,1071.54,1072.47,1071.88,1071.57,1070.47
19,1065.12,1065.59,1065.46,1066.14,1070.48,1070.80,1070.39,1071.57,1072.41,1071.83,1071.6,1070.41
20,1065.08,1065.59,1065.73,1066.14,1070.54,1070.86,1070.36,1071.65,1072.32,1071.76,1071.48,1070.37
21,1065.06,1065.58,1065.82,1066.16,1070.55,1070.81,1070.40,1071.69,1072.21,1071.94,1071.43,1070.32
22,1065.05,1065.59,1065.87,1066.21,1070.55,1070.73,1070.51,1071.79,1072.12,1071.91,1071.38,1070.27
23,1065.30,1065.56,1065.92,1066.21,1070.51,1070.70,1071.10,1071.92,1072.11,1071.88,1071.32,1070.26
24,1065.38,1065.54,1065.96,1066.21,1070.48,1070.76,1071.62,1071.94,1072.01,1071.85,1071.23,1070.2
25,1065.40,1065.52,1065.98,1066.22,1070.51,1070.80,1071.82,1071.99,1072.08,1071.87,1071.2,1070.13
26,1065.40,1065.50,1066.02,1066.25,1070.52,1070.74,1071.90,1072.06,1072.04,1071.81,1071.15,1070.15
27,1065.40,1065.49,1066.03,1066.26,1070.48,1070.75,1071.95,1072.1,1072.01,1071.74,1071.09,1070.13
28,1065.49,1065.49,1066.05,1066.38,1070.56,1070.96,1071.99,1072.3,1072.18,1071.7,1071,1070.16
29,1065.55,1065.47,1066.01,1066.42,1070.69,1071.95,1072.88,1072.14,1071.67,1070.95,1070.11,
30,1065.56,1065.46,1066.02,1066.43,1070.71,1071.85,1073.65,1072.13,1071.59,1070.89,1070.12,
31,1065.58,1066.01,1066.46,1070.70,1073.99,1071.63,1070.86,,,,,

In [ ]:
import re

with urllib.request.urlopen(last_year) as h:
    for line in h:
        print(repr(line))